environment.awareness=prod

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

RESEND_API_KEY=${RESEND_API_KEY}


#On Railway
#SPRING_PROFILES_ACTIVE=prod
#DB_URL=jdbc:mysql://...
#DB_USERNAME=...
#DB_PASSWORD=...
#JWT_SECRET=...
#MAIL_USERNAME=...
#MAIL_PASSWORD=...
#RESEND_API_KEY=...

